/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventarioRouteRouteImport } from './routes/inventario/route'
import { Route as DespachosRouteRouteImport } from './routes/despachos/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DespachosIndexRouteImport } from './routes/despachos/index'
import { Route as InventarioStockRouteImport } from './routes/inventario/stock'
import { Route as InventarioKardexRouteImport } from './routes/inventario/kardex'
import { Route as DespachosCrearRouteImport } from './routes/despachos/crear'
import { Route as DespachosOrdenIdRouteImport } from './routes/despachos/$ordenId'

const InventarioRouteRoute = InventarioRouteRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const DespachosRouteRoute = DespachosRouteRouteImport.update({
  id: '/despachos',
  path: '/despachos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DespachosIndexRoute = DespachosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DespachosRouteRoute,
} as any)
const InventarioStockRoute = InventarioStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => InventarioRouteRoute,
} as any)
const InventarioKardexRoute = InventarioKardexRouteImport.update({
  id: '/kardex',
  path: '/kardex',
  getParentRoute: () => InventarioRouteRoute,
} as any)
const DespachosCrearRoute = DespachosCrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => DespachosRouteRoute,
} as any)
const DespachosOrdenIdRoute = DespachosOrdenIdRouteImport.update({
  id: '/$ordenId',
  path: '/$ordenId',
  getParentRoute: () => DespachosRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/despachos': typeof DespachosRouteRouteWithChildren
  '/inventario': typeof InventarioRouteRouteWithChildren
  '/despachos/$ordenId': typeof DespachosOrdenIdRoute
  '/despachos/crear': typeof DespachosCrearRoute
  '/inventario/kardex': typeof InventarioKardexRoute
  '/inventario/stock': typeof InventarioStockRoute
  '/despachos/': typeof DespachosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventario': typeof InventarioRouteRouteWithChildren
  '/despachos/$ordenId': typeof DespachosOrdenIdRoute
  '/despachos/crear': typeof DespachosCrearRoute
  '/inventario/kardex': typeof InventarioKardexRoute
  '/inventario/stock': typeof InventarioStockRoute
  '/despachos': typeof DespachosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/despachos': typeof DespachosRouteRouteWithChildren
  '/inventario': typeof InventarioRouteRouteWithChildren
  '/despachos/$ordenId': typeof DespachosOrdenIdRoute
  '/despachos/crear': typeof DespachosCrearRoute
  '/inventario/kardex': typeof InventarioKardexRoute
  '/inventario/stock': typeof InventarioStockRoute
  '/despachos/': typeof DespachosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/despachos'
    | '/inventario'
    | '/despachos/$ordenId'
    | '/despachos/crear'
    | '/inventario/kardex'
    | '/inventario/stock'
    | '/despachos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inventario'
    | '/despachos/$ordenId'
    | '/despachos/crear'
    | '/inventario/kardex'
    | '/inventario/stock'
    | '/despachos'
  id:
    | '__root__'
    | '/'
    | '/despachos'
    | '/inventario'
    | '/despachos/$ordenId'
    | '/despachos/crear'
    | '/inventario/kardex'
    | '/inventario/stock'
    | '/despachos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DespachosRouteRoute: typeof DespachosRouteRouteWithChildren
  InventarioRouteRoute: typeof InventarioRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despachos': {
      id: '/despachos'
      path: '/despachos'
      fullPath: '/despachos'
      preLoaderRoute: typeof DespachosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despachos/': {
      id: '/despachos/'
      path: '/'
      fullPath: '/despachos/'
      preLoaderRoute: typeof DespachosIndexRouteImport
      parentRoute: typeof DespachosRouteRoute
    }
    '/inventario/stock': {
      id: '/inventario/stock'
      path: '/stock'
      fullPath: '/inventario/stock'
      preLoaderRoute: typeof InventarioStockRouteImport
      parentRoute: typeof InventarioRouteRoute
    }
    '/inventario/kardex': {
      id: '/inventario/kardex'
      path: '/kardex'
      fullPath: '/inventario/kardex'
      preLoaderRoute: typeof InventarioKardexRouteImport
      parentRoute: typeof InventarioRouteRoute
    }
    '/despachos/crear': {
      id: '/despachos/crear'
      path: '/crear'
      fullPath: '/despachos/crear'
      preLoaderRoute: typeof DespachosCrearRouteImport
      parentRoute: typeof DespachosRouteRoute
    }
    '/despachos/$ordenId': {
      id: '/despachos/$ordenId'
      path: '/$ordenId'
      fullPath: '/despachos/$ordenId'
      preLoaderRoute: typeof DespachosOrdenIdRouteImport
      parentRoute: typeof DespachosRouteRoute
    }
  }
}

interface DespachosRouteRouteChildren {
  DespachosOrdenIdRoute: typeof DespachosOrdenIdRoute
  DespachosCrearRoute: typeof DespachosCrearRoute
  DespachosIndexRoute: typeof DespachosIndexRoute
}

const DespachosRouteRouteChildren: DespachosRouteRouteChildren = {
  DespachosOrdenIdRoute: DespachosOrdenIdRoute,
  DespachosCrearRoute: DespachosCrearRoute,
  DespachosIndexRoute: DespachosIndexRoute,
}

const DespachosRouteRouteWithChildren = DespachosRouteRoute._addFileChildren(
  DespachosRouteRouteChildren,
)

interface InventarioRouteRouteChildren {
  InventarioKardexRoute: typeof InventarioKardexRoute
  InventarioStockRoute: typeof InventarioStockRoute
}

const InventarioRouteRouteChildren: InventarioRouteRouteChildren = {
  InventarioKardexRoute: InventarioKardexRoute,
  InventarioStockRoute: InventarioStockRoute,
}

const InventarioRouteRouteWithChildren = InventarioRouteRoute._addFileChildren(
  InventarioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DespachosRouteRoute: DespachosRouteRouteWithChildren,
  InventarioRouteRoute: InventarioRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
