/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InventarioRouteRouteImport } from './routes/inventario/route'
import { Route as DespachosRouteRouteImport } from './routes/despachos/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PagosIndexRouteImport } from './routes/pagos/index'
import { Route as KardexIndexRouteImport } from './routes/kardex/index'
import { Route as FacturacionIndexRouteImport } from './routes/facturacion/index'
import { Route as DespachosIndexRouteImport } from './routes/despachos/index'
import { Route as InventarioStockRouteImport } from './routes/inventario/stock'
import { Route as InventarioKardexRouteImport } from './routes/inventario/kardex'
import { Route as DespachosCrearRouteImport } from './routes/despachos/crear'
import { Route as PagosPagoIdIndexRouteImport } from './routes/pagos/$pagoId/index'
import { Route as KardexSkuidIndexRouteImport } from './routes/kardex/$skuid/index'
import { Route as FacturacionDocumentoIdIndexRouteImport } from './routes/facturacion/$documentoId/index'
import { Route as DespachosOrdenIdIndexRouteImport } from './routes/despachos/$ordenId/index'
import { Route as PagosCrearPagoTipoRouteImport } from './routes/pagos/crear/$pagoTipo'
import { Route as DespachosOrdenIdEditRouteImport } from './routes/despachos/$ordenId/edit'

const InventarioRouteRoute = InventarioRouteRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const DespachosRouteRoute = DespachosRouteRouteImport.update({
  id: '/despachos',
  path: '/despachos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PagosIndexRoute = PagosIndexRouteImport.update({
  id: '/pagos/',
  path: '/pagos/',
  getParentRoute: () => rootRouteImport,
} as any)
const KardexIndexRoute = KardexIndexRouteImport.update({
  id: '/kardex/',
  path: '/kardex/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionIndexRoute = FacturacionIndexRouteImport.update({
  id: '/facturacion/',
  path: '/facturacion/',
  getParentRoute: () => rootRouteImport,
} as any)
const DespachosIndexRoute = DespachosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DespachosRouteRoute,
} as any)
const InventarioStockRoute = InventarioStockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => InventarioRouteRoute,
} as any)
const InventarioKardexRoute = InventarioKardexRouteImport.update({
  id: '/kardex',
  path: '/kardex',
  getParentRoute: () => InventarioRouteRoute,
} as any)
const DespachosCrearRoute = DespachosCrearRouteImport.update({
  id: '/crear',
  path: '/crear',
  getParentRoute: () => DespachosRouteRoute,
} as any)
const PagosPagoIdIndexRoute = PagosPagoIdIndexRouteImport.update({
  id: '/pagos/$pagoId/',
  path: '/pagos/$pagoId/',
  getParentRoute: () => rootRouteImport,
} as any)
const KardexSkuidIndexRoute = KardexSkuidIndexRouteImport.update({
  id: '/kardex/$skuid/',
  path: '/kardex/$skuid/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionDocumentoIdIndexRoute =
  FacturacionDocumentoIdIndexRouteImport.update({
    id: '/facturacion/$documentoId/',
    path: '/facturacion/$documentoId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const DespachosOrdenIdIndexRoute = DespachosOrdenIdIndexRouteImport.update({
  id: '/$ordenId/',
  path: '/$ordenId/',
  getParentRoute: () => DespachosRouteRoute,
} as any)
const PagosCrearPagoTipoRoute = PagosCrearPagoTipoRouteImport.update({
  id: '/pagos/crear/$pagoTipo',
  path: '/pagos/crear/$pagoTipo',
  getParentRoute: () => rootRouteImport,
} as any)
const DespachosOrdenIdEditRoute = DespachosOrdenIdEditRouteImport.update({
  id: '/$ordenId/edit',
  path: '/$ordenId/edit',
  getParentRoute: () => DespachosRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/despachos': typeof DespachosRouteRouteWithChildren
  '/inventario': typeof InventarioRouteRouteWithChildren
  '/despachos/crear': typeof DespachosCrearRoute
  '/inventario/kardex': typeof InventarioKardexRoute
  '/inventario/stock': typeof InventarioStockRoute
  '/despachos/': typeof DespachosIndexRoute
  '/facturacion/': typeof FacturacionIndexRoute
  '/kardex/': typeof KardexIndexRoute
  '/pagos/': typeof PagosIndexRoute
  '/despachos/$ordenId/edit': typeof DespachosOrdenIdEditRoute
  '/pagos/crear/$pagoTipo': typeof PagosCrearPagoTipoRoute
  '/despachos/$ordenId/': typeof DespachosOrdenIdIndexRoute
  '/facturacion/$documentoId/': typeof FacturacionDocumentoIdIndexRoute
  '/kardex/$skuid/': typeof KardexSkuidIndexRoute
  '/pagos/$pagoId/': typeof PagosPagoIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inventario': typeof InventarioRouteRouteWithChildren
  '/despachos/crear': typeof DespachosCrearRoute
  '/inventario/kardex': typeof InventarioKardexRoute
  '/inventario/stock': typeof InventarioStockRoute
  '/despachos': typeof DespachosIndexRoute
  '/facturacion': typeof FacturacionIndexRoute
  '/kardex': typeof KardexIndexRoute
  '/pagos': typeof PagosIndexRoute
  '/despachos/$ordenId/edit': typeof DespachosOrdenIdEditRoute
  '/pagos/crear/$pagoTipo': typeof PagosCrearPagoTipoRoute
  '/despachos/$ordenId': typeof DespachosOrdenIdIndexRoute
  '/facturacion/$documentoId': typeof FacturacionDocumentoIdIndexRoute
  '/kardex/$skuid': typeof KardexSkuidIndexRoute
  '/pagos/$pagoId': typeof PagosPagoIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/despachos': typeof DespachosRouteRouteWithChildren
  '/inventario': typeof InventarioRouteRouteWithChildren
  '/despachos/crear': typeof DespachosCrearRoute
  '/inventario/kardex': typeof InventarioKardexRoute
  '/inventario/stock': typeof InventarioStockRoute
  '/despachos/': typeof DespachosIndexRoute
  '/facturacion/': typeof FacturacionIndexRoute
  '/kardex/': typeof KardexIndexRoute
  '/pagos/': typeof PagosIndexRoute
  '/despachos/$ordenId/edit': typeof DespachosOrdenIdEditRoute
  '/pagos/crear/$pagoTipo': typeof PagosCrearPagoTipoRoute
  '/despachos/$ordenId/': typeof DespachosOrdenIdIndexRoute
  '/facturacion/$documentoId/': typeof FacturacionDocumentoIdIndexRoute
  '/kardex/$skuid/': typeof KardexSkuidIndexRoute
  '/pagos/$pagoId/': typeof PagosPagoIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/despachos'
    | '/inventario'
    | '/despachos/crear'
    | '/inventario/kardex'
    | '/inventario/stock'
    | '/despachos/'
    | '/facturacion/'
    | '/kardex/'
    | '/pagos/'
    | '/despachos/$ordenId/edit'
    | '/pagos/crear/$pagoTipo'
    | '/despachos/$ordenId/'
    | '/facturacion/$documentoId/'
    | '/kardex/$skuid/'
    | '/pagos/$pagoId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/inventario'
    | '/despachos/crear'
    | '/inventario/kardex'
    | '/inventario/stock'
    | '/despachos'
    | '/facturacion'
    | '/kardex'
    | '/pagos'
    | '/despachos/$ordenId/edit'
    | '/pagos/crear/$pagoTipo'
    | '/despachos/$ordenId'
    | '/facturacion/$documentoId'
    | '/kardex/$skuid'
    | '/pagos/$pagoId'
  id:
    | '__root__'
    | '/'
    | '/despachos'
    | '/inventario'
    | '/despachos/crear'
    | '/inventario/kardex'
    | '/inventario/stock'
    | '/despachos/'
    | '/facturacion/'
    | '/kardex/'
    | '/pagos/'
    | '/despachos/$ordenId/edit'
    | '/pagos/crear/$pagoTipo'
    | '/despachos/$ordenId/'
    | '/facturacion/$documentoId/'
    | '/kardex/$skuid/'
    | '/pagos/$pagoId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DespachosRouteRoute: typeof DespachosRouteRouteWithChildren
  InventarioRouteRoute: typeof InventarioRouteRouteWithChildren
  FacturacionIndexRoute: typeof FacturacionIndexRoute
  KardexIndexRoute: typeof KardexIndexRoute
  PagosIndexRoute: typeof PagosIndexRoute
  PagosCrearPagoTipoRoute: typeof PagosCrearPagoTipoRoute
  FacturacionDocumentoIdIndexRoute: typeof FacturacionDocumentoIdIndexRoute
  KardexSkuidIndexRoute: typeof KardexSkuidIndexRoute
  PagosPagoIdIndexRoute: typeof PagosPagoIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despachos': {
      id: '/despachos'
      path: '/despachos'
      fullPath: '/despachos'
      preLoaderRoute: typeof DespachosRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagos/': {
      id: '/pagos/'
      path: '/pagos'
      fullPath: '/pagos/'
      preLoaderRoute: typeof PagosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kardex/': {
      id: '/kardex/'
      path: '/kardex'
      fullPath: '/kardex/'
      preLoaderRoute: typeof KardexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion/': {
      id: '/facturacion/'
      path: '/facturacion'
      fullPath: '/facturacion/'
      preLoaderRoute: typeof FacturacionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despachos/': {
      id: '/despachos/'
      path: '/'
      fullPath: '/despachos/'
      preLoaderRoute: typeof DespachosIndexRouteImport
      parentRoute: typeof DespachosRouteRoute
    }
    '/inventario/stock': {
      id: '/inventario/stock'
      path: '/stock'
      fullPath: '/inventario/stock'
      preLoaderRoute: typeof InventarioStockRouteImport
      parentRoute: typeof InventarioRouteRoute
    }
    '/inventario/kardex': {
      id: '/inventario/kardex'
      path: '/kardex'
      fullPath: '/inventario/kardex'
      preLoaderRoute: typeof InventarioKardexRouteImport
      parentRoute: typeof InventarioRouteRoute
    }
    '/despachos/crear': {
      id: '/despachos/crear'
      path: '/crear'
      fullPath: '/despachos/crear'
      preLoaderRoute: typeof DespachosCrearRouteImport
      parentRoute: typeof DespachosRouteRoute
    }
    '/pagos/$pagoId/': {
      id: '/pagos/$pagoId/'
      path: '/pagos/$pagoId'
      fullPath: '/pagos/$pagoId/'
      preLoaderRoute: typeof PagosPagoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kardex/$skuid/': {
      id: '/kardex/$skuid/'
      path: '/kardex/$skuid'
      fullPath: '/kardex/$skuid/'
      preLoaderRoute: typeof KardexSkuidIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion/$documentoId/': {
      id: '/facturacion/$documentoId/'
      path: '/facturacion/$documentoId'
      fullPath: '/facturacion/$documentoId/'
      preLoaderRoute: typeof FacturacionDocumentoIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despachos/$ordenId/': {
      id: '/despachos/$ordenId/'
      path: '/$ordenId'
      fullPath: '/despachos/$ordenId/'
      preLoaderRoute: typeof DespachosOrdenIdIndexRouteImport
      parentRoute: typeof DespachosRouteRoute
    }
    '/pagos/crear/$pagoTipo': {
      id: '/pagos/crear/$pagoTipo'
      path: '/pagos/crear/$pagoTipo'
      fullPath: '/pagos/crear/$pagoTipo'
      preLoaderRoute: typeof PagosCrearPagoTipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/despachos/$ordenId/edit': {
      id: '/despachos/$ordenId/edit'
      path: '/$ordenId/edit'
      fullPath: '/despachos/$ordenId/edit'
      preLoaderRoute: typeof DespachosOrdenIdEditRouteImport
      parentRoute: typeof DespachosRouteRoute
    }
  }
}

interface DespachosRouteRouteChildren {
  DespachosCrearRoute: typeof DespachosCrearRoute
  DespachosIndexRoute: typeof DespachosIndexRoute
  DespachosOrdenIdEditRoute: typeof DespachosOrdenIdEditRoute
  DespachosOrdenIdIndexRoute: typeof DespachosOrdenIdIndexRoute
}

const DespachosRouteRouteChildren: DespachosRouteRouteChildren = {
  DespachosCrearRoute: DespachosCrearRoute,
  DespachosIndexRoute: DespachosIndexRoute,
  DespachosOrdenIdEditRoute: DespachosOrdenIdEditRoute,
  DespachosOrdenIdIndexRoute: DespachosOrdenIdIndexRoute,
}

const DespachosRouteRouteWithChildren = DespachosRouteRoute._addFileChildren(
  DespachosRouteRouteChildren,
)

interface InventarioRouteRouteChildren {
  InventarioKardexRoute: typeof InventarioKardexRoute
  InventarioStockRoute: typeof InventarioStockRoute
}

const InventarioRouteRouteChildren: InventarioRouteRouteChildren = {
  InventarioKardexRoute: InventarioKardexRoute,
  InventarioStockRoute: InventarioStockRoute,
}

const InventarioRouteRouteWithChildren = InventarioRouteRoute._addFileChildren(
  InventarioRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DespachosRouteRoute: DespachosRouteRouteWithChildren,
  InventarioRouteRoute: InventarioRouteRouteWithChildren,
  FacturacionIndexRoute: FacturacionIndexRoute,
  KardexIndexRoute: KardexIndexRoute,
  PagosIndexRoute: PagosIndexRoute,
  PagosCrearPagoTipoRoute: PagosCrearPagoTipoRoute,
  FacturacionDocumentoIdIndexRoute: FacturacionDocumentoIdIndexRoute,
  KardexSkuidIndexRoute: KardexSkuidIndexRoute,
  PagosPagoIdIndexRoute: PagosPagoIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
